services:
  redis:
    container_name: redis
    image: redis:alpine    
    ports:
    - "6379:6379"
    networks:
    - net
    volumes:
    - redis-data:/data
  study03:
    container_name: study03
    image: eeengcs/study03:1.0.0-SNAPSHOT
    depends_on:
    - redis
    ports:
    - "8280:8080"
    networks:
    - net
networks:
  net:
volumes:
  redis-data: